apiVersion: apps/v1
kind: Deployment
metadata:
  name: boetest
spec:
  selector:
    matchLabels:
      run: load-balancer-example
  replicas: 2
  template:
    metadata:
      labels:
        run: load-balancer-example
    spec:
      containers:
        - name: boetest
          #image: gcr.io/google-samples/node-hello:1.0
          image: ip-172-31-32-147.us-west-2.compute.internal/library/boetest:latest
          ports:
            - containerPort: 8080
              protocol: TCP
