apiVersion: apps/v1
kind: Deployment
metadata:
  name: boetest
spec:
  selector:
    matchLabels:
      run: load-balancer-example
  replicas: 2
  template:
    metadata:
      labels:
        run: load-balancer-example
    spec:
      containers:
        - name: boetest
          #image: gcr.io/google-samples/node-hello:1.0
          image: 34.216.36.61/library/boetest
          ports:
            - containerPort: 80
              protocol: TCP
      imagePullSecrets:
        - name: registry-harbor
