apiVersion: apps/v1
kind: Deployment
metadata:
  name: boetest
spec:
  selector:
    matchLabels:
      run: load-balancer-example
  replicas: 2
  template:
    metadata:
      labels:
        run: load-balancer-example
    spec:
      containers:
        - name: boetest
          #image: gcr.io/google-samples/node-hello:1.0
          image: ec2-34-216-36-61.us-west-2.compute.amazonaws.com/library/boetest:latest
          ports:
            - containerPort: 8080
              protocol: TCP
